server:
  port: 9296
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShubhamGuptaK07/spring-app-config
          clone-on-start: true