server:
  port: 9296
spring:
  application:
    name: config-server
  clod:
    config:
      server:
        git:
          url: https://github.com/ShubhamGuptaK07/spring-app-config
          clone-on-start: true